### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Katsute** [KatsuteDev/BackgroundX#5]
This extension is currently in early access, Firefox support will come later.

#### TODO

- [x] Add banner in options on Firefox about MV3 BS

Verify that the following works on Firefox:

 - [x] Options menu ~~(also on click)~~
 - [x] Storage sync
 - [x] Setting import/export/~~reset~~
 - [ ] CSS nesting/has selector compatibility
 - [x] JS/CSS injection into VSCode
 - [ ] JS/CSS injection into Codespaces

Prior to release:

 - [x] Notice about Firefox MV3 permission BS
 - [x] Pre-release generate UUID from MV2
 - [x] Update README
